extend type Appointment {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Appointment", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Appointment` table.
  """
  _count: Int! @fdc_generated(from: "Appointment", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `appointmentDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  appointmentDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.appointmentDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `appointmentTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  appointmentTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.appointmentTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `location` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  location_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.location", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `patientId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  patientId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.patientId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `providerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  providerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.providerId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `reason` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  reason_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.reason", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Appointment` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Appointment.status", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `appointmentDate` field in the `Appointment` table.
  """
  appointmentDate_min: Date @fdc_generated(from: "Appointment.appointmentDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `createdAt` field in the `Appointment` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Appointment.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `appointmentDate` field in the `Appointment` table.
  """
  appointmentDate_max: Date @fdc_generated(from: "Appointment.appointmentDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `createdAt` field in the `Appointment` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Appointment.createdAt", purpose: QUERY_MAX)
}
extend type MedicalRecord {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "MedicalRecord", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `MedicalRecord` table.
  """
  _count: Int! @fdc_generated(from: "MedicalRecord", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MedicalRecord` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MedicalRecord.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MedicalRecord` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MedicalRecord.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MedicalRecord` table where the `diagnosisCode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  diagnosisCode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MedicalRecord.diagnosisCode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MedicalRecord` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MedicalRecord.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MedicalRecord` table where the `patientId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  patientId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MedicalRecord.patientId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MedicalRecord` table where the `providerNotes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  providerNotes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MedicalRecord.providerNotes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MedicalRecord` table where the `recordDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  recordDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MedicalRecord.recordDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MedicalRecord` table where the `recordType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  recordType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MedicalRecord.recordType", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `MedicalRecord` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "MedicalRecord.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `recordDate` field in the `MedicalRecord` table.
  """
  recordDate_min: Date @fdc_generated(from: "MedicalRecord.recordDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `MedicalRecord` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "MedicalRecord.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `recordDate` field in the `MedicalRecord` table.
  """
  recordDate_max: Date @fdc_generated(from: "MedicalRecord.recordDate", purpose: QUERY_MAX)
}
extend type Message {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Message", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Message` table.
  """
  _count: Int! @fdc_generated(from: "Message", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `attachmentUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  attachmentUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.attachmentUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `isRead` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isRead_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.isRead", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `messageContent` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  messageContent_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.messageContent", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `receiverId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  receiverId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.receiverId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `senderId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  senderId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.senderId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `sentAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sentAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.sentAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `subject` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  subject_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.subject", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `sentAt` field in the `Message` table.
  """
  sentAt_min: Timestamp @fdc_generated(from: "Message.sentAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `sentAt` field in the `Message` table.
  """
  sentAt_max: Timestamp @fdc_generated(from: "Message.sentAt", purpose: QUERY_MAX)
}
extend type Prescription {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Prescription", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Prescription` table.
  """
  _count: Int! @fdc_generated(from: "Prescription", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `dosage` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dosage_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.dosage", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `endDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.endDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `frequency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  frequency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.frequency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `instructions` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  instructions_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.instructions", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `medicationName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  medicationName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.medicationName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `patientId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  patientId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.patientId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `providerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  providerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.providerId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `refillsRemaining` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  refillsRemaining_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.refillsRemaining", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Prescription` table where the `startDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Prescription.startDate", purpose: QUERY_COUNT)
  """
  ✨ Sum the `refillsRemaining` field in the `Prescription` table.
  """
  refillsRemaining_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Prescription.refillsRemaining", purpose: QUERY_SUM)
  """
  ✨ Average the `refillsRemaining` field in the `Prescription` table.
  """
  refillsRemaining_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Prescription.refillsRemaining", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Prescription` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Prescription.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `endDate` field in the `Prescription` table.
  """
  endDate_min: Date @fdc_generated(from: "Prescription.endDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `refillsRemaining` field in the `Prescription` table.
  """
  refillsRemaining_min: Int @fdc_generated(from: "Prescription.refillsRemaining", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startDate` field in the `Prescription` table.
  """
  startDate_min: Date @fdc_generated(from: "Prescription.startDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Prescription` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Prescription.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `endDate` field in the `Prescription` table.
  """
  endDate_max: Date @fdc_generated(from: "Prescription.endDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `refillsRemaining` field in the `Prescription` table.
  """
  refillsRemaining_max: Int @fdc_generated(from: "Prescription.refillsRemaining", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startDate` field in the `Prescription` table.
  """
  startDate_max: Date @fdc_generated(from: "Prescription.startDate", purpose: QUERY_MAX)
}
extend type User {
  """
  ✨ List `Appointment` objects in a one-to-many relationship (where `Appointment`.`patient` is this object).
  """
  appointments_on_patient(
    """
    Filter condition to narrow down the query results.
    """
    where: Appointment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Appointment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Appointment_Having
  ): [Appointment!]! @fdc_generated(from: "Appointment.patient", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Appointment` objects in a one-to-many relationship (where `Appointment`.`provider` is this object).
  """
  appointments_on_provider(
    """
    Filter condition to narrow down the query results.
    """
    where: Appointment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Appointment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Appointment_Having
  ): [Appointment!]! @fdc_generated(from: "Appointment.provider", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `MedicalRecord` objects in a one-to-many relationship (where `MedicalRecord`.`patient` is this object).
  """
  medicalRecords_on_patient(
    """
    Filter condition to narrow down the query results.
    """
    where: MedicalRecord_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MedicalRecord_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MedicalRecord_Having
  ): [MedicalRecord!]! @fdc_generated(from: "MedicalRecord.patient", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Message` objects in a one-to-many relationship (where `Message`.`receiver` is this object).
  """
  messages_on_receiver(
    """
    Filter condition to narrow down the query results.
    """
    where: Message_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Message_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Message_Having
  ): [Message!]! @fdc_generated(from: "Message.receiver", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Message` objects in a one-to-many relationship (where `Message`.`sender` is this object).
  """
  messages_on_sender(
    """
    Filter condition to narrow down the query results.
    """
    where: Message_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Message_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Message_Having
  ): [Message!]! @fdc_generated(from: "Message.sender", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Prescription` objects in a one-to-many relationship (where `Prescription`.`patient` is this object).
  """
  prescriptions_on_patient(
    """
    Filter condition to narrow down the query results.
    """
    where: Prescription_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Prescription_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Prescription_Having
  ): [Prescription!]! @fdc_generated(from: "Prescription.patient", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Prescription` objects in a one-to-many relationship (where `Prescription`.`provider` is this object).
  """
  prescriptions_on_provider(
    """
    Filter condition to narrow down the query results.
    """
    where: Prescription_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Prescription_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Prescription_Having
  ): [Prescription!]! @fdc_generated(from: "Prescription.provider", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `address` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  address_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.address", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `dateOfBirth` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dateOfBirth_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.dateOfBirth", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `firstName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  firstName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.firstName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `lastName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.lastName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `passwordHash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  passwordHash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.passwordHash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `phoneNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phoneNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.phoneNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `profilePictureUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  profilePictureUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.profilePictureUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `userType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.userType", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `dateOfBirth` field in the `User` table.
  """
  dateOfBirth_min: Date @fdc_generated(from: "User.dateOfBirth", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `dateOfBirth` field in the `User` table.
  """
  dateOfBirth_max: Date @fdc_generated(from: "User.dateOfBirth", purpose: QUERY_MAX)
}
