mutation SeedData @auth(level: USER) {
  user_insertMany(data: [
    {
      id: "550e8400-e29b-41d4-a716-446655440000",
      firstName: "John",
      lastName: "Doe",
      email: "john.doe@example.com",
      passwordHash: "somehash",
      userType: "patient"
    },
    {
      id: "550e8400-e29b-41d4-a716-446655440001",
      firstName: "Jane",
      lastName: "Smith",
      email: "jane.smith@example.com",
      passwordHash: "anotherhash",
      userType: "provider"
    }
  ])
}